server {
  listen 80;
  server_name example.com;

  root /path/to/document/root/;

  location = /cron {
    lua_code_cache on;
    default_type text/html;
    set $ophal_script_name /cron.lua;

    set_by_lua $_ '
      require "lfs".chdir(ngx.var.document_root)
      return nil
    ';

    content_by_lua_file $document_root/cron.lua;
  }

  location = /__ophal_index__ {
    internal;
    lua_code_cache on;
    default_type text/html;
    set $ophal_script_name /index.lua;

    set_by_lua $_ '
      require "lfs".chdir(ngx.var.document_root)
      return nil
    ';

    content_by_lua_file $document_root/index.lua;
  }

  location = /index.lua { return 404; }
  location = /cron.lua { return 404; }
  location = /settings.lua { return 404; }
  location = /vault.lua { return 404; }
  location ^~ /settings/ { return 404; }
  location ^~ /includes/ { return 404; }
  location ^~ /modules/ { return 404; }

  location ~ \.lua$ {
    return 404;
  }

  ## All static files will be served directly.
  location ~* ^.+\.(?:css|cur|js|jpg|jpeg|gif|htc|ico|png|html|xml|less|ttf|pdf|map)$ {
    try_files $uri =404;
    access_log off;
    expires 30d;
    ## No need to bleed constant updates. Send the all shebang in one
    ## fell swoop.
    tcp_nodelay off;
    ## Set the OS file cache.
    open_file_cache max=3000 inactive=120s;
    open_file_cache_valid 45s;
    open_file_cache_min_uses 2;
    open_file_cache_errors off;
  }

  location / {
    try_files $uri /__ophal_index__;
  }

  access_log /var/log/nginx/example.com-access.log;
  error_log /var/log/nginx/example.com-error.log;
}
