--[[ One source of randomness for everything that has to be unguessable.

  Session ids, CSRF tokens, password salts and the installer's site hash were
  each generated by whatever was to hand: `uuid.new()` for the first three and,
  when no uuid binding was installed, this for the fourth --

      math.randomseed(os.time())
      return ('install-%d-%06d'):format(os.time(), math.random(0, 999999))

  -- a string that carries its own seed, so its entropy is not small but zero.
  `uuid.new()` is better and still wrong to rest on: production is told to
  install `luuid`, a binding to libuuid, which can generate time-and-MAC based
  UUIDs as well as random ones. Which one `new()` picks is that library's
  default, not this project's decision, and a session id is not a thing to hold
  by an unpinned default.

  So secrets come from here, and here reads a CSPRNG or raises. There is
  deliberately **no** fallback to `math.random`: a weak secret that works is
  worse than a loud failure, because nothing downstream can tell the difference.

  Two sources, in order:

  - `resty.random.bytes(n, true)` under OpenResty, whose `true` asks for
    cryptographic strength rather than the fast PRNG the same function returns
    without it.
  - `/dev/urandom` otherwise, which is what the CLI and the unit suite get. It
    is opened once and kept, because reopening it per call is the expensive part
    and the handle is per worker.

  `/dev/urandom` and never `/dev/random`: on Linux the two draw from the same
  pool once it is initialised, and only the second blocks.
]]

local M = {}

local format, floor = string.format, math.floor
local unpack = unpack or table.unpack

local source

local function fail(message)
  error('random: ' .. message, 0)
end

local function resty_source()
  local ok, random = pcall(require, 'resty.random')

  if not ok or type(random) ~= 'table' or type(random.bytes) ~= 'function' then
    return nil
  end

  return function(n)
    -- The second argument is what makes this cryptographically strong. Without
    -- it the same function answers from a fast PRNG, which is the trap this
    -- module exists to avoid stepping into by accident.
    local bytes = random.bytes(n, true)

    if type(bytes) ~= 'string' or #bytes ~= n then
      return nil
    end

    return bytes
  end
end

local function urandom_source()
  local handle = io.open('/dev/urandom', 'rb')

  if not handle then
    return nil
  end

  return function(n)
    local bytes = handle:read(n)

    if type(bytes) ~= 'string' or #bytes ~= n then
      -- A short read means the handle has gone; drop it so the next call
      -- resolves a source again rather than returning something shorter than
      -- asked for.
      source = nil
      return nil
    end

    return bytes
  end
end

local function current()
  if source == nil then
    source = resty_source() or urandom_source()

    if source == nil then
      fail('no cryptographic random source: neither resty.random nor '
        .. '/dev/urandom is available')
    end
  end

  return source
end

--[[ `n` cryptographically random bytes, or an error. ]]
function M.bytes(n)
  local count = tonumber(n)
  local bytes

  if count == nil or count < 1 or floor(count) ~= count then
    fail('bytes needs a positive whole number, got ' .. tostring(n))
  end

  bytes = current()(count)

  if bytes == nil then
    fail('random source returned nothing')
  end

  return bytes
end

--[[ `n` random bytes as lowercase hex, so the result is 2n characters. ]]
function M.hex(n)
  return (M.bytes(n):gsub('.', function(c)
    return format('%02x', c:byte())
  end))
end

--[[ A random (version 4) UUID, in the usual 8-4-4-4-12 spelling.

  The format matters rather than the flavour: `session_init()` accepts an id
  from the cookie only when `uuid.isvalid()` says it looks like one, so a
  session id has to keep that shape or every request would reject the cookie it
  just set and issue another.

  Six bits of the sixteen bytes are spent on the version and variant fields
  RFC 4122 defines, leaving 122 random ones.
]]
function M.uuid()
  local b = {M.bytes(16):byte(1, 16)}

  b[7] = b[7] % 16 + 64    -- version 4:  0100xxxx
  b[9] = b[9] % 64 + 128   -- variant 10: 10xxxxxx

  return format(
    '%02x%02x%02x%02x-%02x%02x-%02x%02x-%02x%02x-%02x%02x%02x%02x%02x%02x',
    unpack(b))
end

--[[ For the unit suite, which drives the no-source path. ]]
function M.reset()
  source = nil
end

return M
